version: "3.9"

services:
  backend:
    image: local
    build: .  # поиск образа не из docker-образов на сайте, а из Dockerfile
    container_name: backend
    stdin_open: true  # для возможности взаимодействия с консолью контейнера
    tty: true  # для возможности взаимодействия с консолью контейнера
    ports:
      - "8000:8000"

  memcached:
    image: memcached:1.6.9
    container_name: memcached
    ports:
      - "11211:11211"

  rabbitmq:
    image: rabbitmq:3.9-management  # только с версией managment
    container_name: rabbitmq
    env_file: .env  # для работы с файлом .env (имя и пароль)
    ports:
      - "5672:5672"
      - "15672:15672"


  postgres:
    image: postgres:15.2-alpine
    container_name: postgres
    env_file: .env
    ports:
      - "5432:5432"
    volumes:  # для того, чтобы после установки контейнеров база данных не удалялась
      - db_data:/var/lib/postgresql/data  # место хранения БД при остановленных контенерах

volumes:
  db_data: {}
