# Generated by Django 4.1.7 on 2023-02-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
